# Generated by Codex
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_organization_membership_and_user_email_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firewall', models.CharField(blank=True, max_length=120)),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('azure', 'Microsoft Azure'), ('gcp', 'Google Cloud'), ('contabo', 'Contabo'), ('hetzner', 'Hetzner'), ('onprem', 'On-Prem'), ('other', 'Otro')], default='other', max_length=30)),
                ('resource_name', models.CharField(max_length=160)),
                ('resource_type', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('private_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('log_type', models.CharField(blank=True, max_length=80)),
                ('raw_log', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_artifacts', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_provider_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider artifact',
                'verbose_name_plural': 'Provider artifacts',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='providerartifact',
            index=models.Index(fields=['organization', 'provider'], name='ultrifire_p_organiz_2b3e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='providerartifact',
            index=models.Index(fields=['organization', 'private_ip'], name='ultrifire_p_organiz_b61020_idx'),
        ),
        migrations.AddIndex(
            model_name='providerartifact',
            index=models.Index(fields=['organization', 'firewall'], name='ultrifire_p_organiz_b2a656_idx'),
        ),
    ]
