# Generated by Django 5.1.7 on 2026-04-15 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_asset_organization"),
        ("findings", "0002_finding_organization"),
        ("knowledge_base", "0002_referencelink_end_of_life_rule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="findings",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="end_of_life_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="knowledge_base.endofliferule",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="reference",
            field=models.URLField(blank=True),
        ),
    ]
