# Generated by Django 5.1.7 on 2026-04-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0003_finding_asset_finding_end_of_life_rule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="correlation_trace",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
