# Generated by Django 5.1.7 on 2026-04-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0004_finding_correlation_trace"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="ai_confidence",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="finding",
            name="ai_cwe",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="finding",
            name="ai_enrichment",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="finding",
            name="ai_impact",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="ai_owasp_category",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="finding",
            name="ai_priority_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="ai_remediation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="ai_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="ai_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="finding",
            name="ai_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
