# Generated by Django 5.1.7 on 2026-04-15 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencelink",
            name="end_of_life_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="knowledge_base.endofliferule",
            ),
        ),
        migrations.AddField(
            model_name="referencelink",
            name="misconfiguration_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="knowledge_base.misconfigurationrule",
            ),
        ),
        migrations.AlterField(
            model_name="endofliferule",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_rules",
                to="knowledge_base.product",
            ),
        ),
        migrations.AlterField(
            model_name="misconfigurationrule",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_rules",
                to="knowledge_base.product",
            ),
        ),
        migrations.AlterField(
            model_name="referencelink",
            name="vulnerability_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="knowledge_base.vulnerabilityrule",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityrule",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_rules",
                to="knowledge_base.product",
            ),
        ),
        migrations.CreateModel(
            name="ProductAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias", models.CharField(max_length=120, unique=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="knowledge_base.product",
                    ),
                ),
            ],
            options={
                "ordering": ["alias"],
            },
        ),
        migrations.DeleteModel(
            name="ProductVersionRule",
        ),
    ]
