# Generated by Django 5.1.7 on 2026-04-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0002_referencelink_end_of_life_rule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofliferule",
            name="evidence_type",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="endofliferule",
            name="required_state",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="endofliferule",
            name="service_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="endofliferule",
            name="version_operator",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="endofliferule",
            name="version_value",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="misconfigurationrule",
            name="evidence_type",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="misconfigurationrule",
            name="required_state",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="misconfigurationrule",
            name="service_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="misconfigurationrule",
            name="version_operator",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="misconfigurationrule",
            name="version_value",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vulnerabilityrule",
            name="evidence_type",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="vulnerabilityrule",
            name="required_state",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vulnerabilityrule",
            name="service_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="vulnerabilityrule",
            name="version_operator",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="vulnerabilityrule",
            name="version_value",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
