# Generated by Django 5.1.7 on 2026-04-15 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0003_endofliferule_evidence_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisorySyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(default="NVD", max_length=20)),
                ("command", models.CharField(max_length=120)),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_fetched", models.PositiveIntegerField(default=0)),
                ("total_created", models.PositiveIntegerField(default=0)),
                ("total_updated", models.PositiveIntegerField(default=0)),
                ("total_errors", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalAdvisory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("NVD", "NVD")], default="NVD", max_length=20
                    ),
                ),
                ("cve_id", models.CharField(db_index=True, max_length=32, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_modified_at", models.DateTimeField(blank=True, null=True)),
                ("severity", models.CharField(blank=True, max_length=20)),
                (
                    "cvss_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("cvss_vector", models.CharField(blank=True, max_length=255)),
                ("cvss_version", models.CharField(blank=True, max_length=20)),
                ("has_kev", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-last_modified_at", "cve_id"],
                "indexes": [
                    models.Index(
                        fields=["source", "last_modified_at"],
                        name="knowledge_b_source_648456_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalAdvisoryCpeMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vulnerable", models.BooleanField(default=True)),
                ("criteria", models.CharField(max_length=1024)),
                ("match_criteria_id", models.CharField(blank=True, max_length=80)),
                (
                    "version_start_including",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "version_start_excluding",
                    models.CharField(blank=True, max_length=120),
                ),
                ("version_end_including", models.CharField(blank=True, max_length=120)),
                ("version_end_excluding", models.CharField(blank=True, max_length=120)),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpe_matches",
                        to="knowledge_base.externaladvisory",
                    ),
                ),
            ],
            options={
                "ordering": ["advisory_id", "id"],
                "unique_together": {("advisory", "criteria", "match_criteria_id")},
            },
        ),
        migrations.CreateModel(
            name="ExternalAdvisoryReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                ("source", models.CharField(blank=True, max_length=120)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="knowledge_base.externaladvisory",
                    ),
                ),
            ],
            options={
                "ordering": ["advisory_id", "id"],
                "unique_together": {("advisory", "url")},
            },
        ),
        migrations.CreateModel(
            name="ExternalAdvisoryWeakness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("cwe_id", models.CharField(blank=True, max_length=80)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weaknesses",
                        to="knowledge_base.externaladvisory",
                    ),
                ),
            ],
            options={
                "ordering": ["advisory_id", "cwe_id", "id"],
                "indexes": [
                    models.Index(
                        fields=["cwe_id"], name="knowledge_b_cwe_id_e937af_idx"
                    )
                ],
            },
        ),
    ]
