# Generated by Django 5.1.7 on 2026-04-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0004_advisorysyncjob_externaladvisory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaladvisoryreference",
            name="source",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="externaladvisoryreference",
            name="url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="externaladvisoryweakness",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="externaladvisoryweakness",
            name="source",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
