# Generated by Django 5.1.7 on 2026-04-15 18:53

import django.db.models.deletion
from django.db import migrations, models


DEDUP_WEAKNESSES_SQL = """
DELETE FROM knowledge_base_externaladvisoryweakness target
USING knowledge_base_externaladvisoryweakness duplicate
WHERE target.advisory_id = duplicate.advisory_id
  AND target.cwe_id = duplicate.cwe_id
  AND target.id > duplicate.id;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0005_alter_externaladvisoryreference_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAdvisoryMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("metric_type", models.CharField(max_length=40)),
                ("cvss_version", models.CharField(blank=True, max_length=20)),
                (
                    "base_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("base_severity", models.CharField(blank=True, max_length=20)),
                ("vector_string", models.CharField(blank=True, max_length=255)),
                (
                    "exploitability_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "impact_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["advisory_id", "metric_type", "source", "id"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="externaladvisorycpematch",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="externaladvisorycpematch",
            constraint=models.UniqueConstraint(
                fields=(
                    "advisory",
                    "criteria",
                    "version_start_including",
                    "version_start_excluding",
                    "version_end_including",
                    "version_end_excluding",
                ),
                name="kb_unique_advisory_cpe_signature",
            ),
        ),
        migrations.RunSQL(
            sql=DEDUP_WEAKNESSES_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="externaladvisoryweakness",
            constraint=models.UniqueConstraint(
                fields=("advisory", "cwe_id"), name="kb_unique_advisory_cwe"
            ),
        ),
        migrations.AddField(
            model_name="externaladvisorymetric",
            name="advisory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="knowledge_base.externaladvisory",
            ),
        ),
        migrations.AddConstraint(
            model_name="externaladvisorymetric",
            constraint=models.UniqueConstraint(
                fields=("advisory", "source", "metric_type", "cvss_version"),
                name="kb_unique_advisory_metric_signature",
            ),
        ),
    ]
