# Generated by Django 5.1.7 on 2026-04-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0006_externaladvisorymetric_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advisorysyncjob",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="created_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="error_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="filters_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="ignored_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="job_type",
            field=models.CharField(default="sync_nvd", max_length=120),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="last_start_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="last_successful_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="page_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="updated_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="advisorysyncjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="advisorysyncjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
