# Generated by Django 5.1.7 on 2026-04-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0007_alter_advisorysyncjob_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisorysyncjob",
            name="current_start_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="current_window_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="current_window_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="fetched_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advisorysyncjob",
            name="processed_pages",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
