# Generated by Django 5.1.7 on 2026-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scan_profiles", "0002_scanprofile_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanprofile",
            name="web_scan_defaults",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scanprofile",
            name="web_scan_preset",
            field=models.CharField(default="medium", max_length=12),
        ),
    ]
