# Generated by Django 5.1.7 on 2026-04-15 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0002_multitenant_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rawevidence",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="rawevidence",
            name="raw_output",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scanexecution",
            name="engine_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scanexecution",
            name="launched_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="launched_scans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="servicefinding",
            name="extrainfo",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="servicefinding",
            name="normalized_product",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="servicefinding",
            name="scripts",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="webfinding",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
