# Generated by Django 5.1.7 on 2026-04-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0003_rawevidence_metadata_rawevidence_raw_output_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicefinding",
            name="normalized_version",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="servicefinding",
            name="raw_version",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
