# Generated by Django 5.1.7 on 2026-04-17 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0004_servicefinding_normalized_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanexecution",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scanexecution",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scanexecution",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="scanexecution",
            name="progress_stage",
            field=models.CharField(blank=True, default="queued", max_length=40),
        ),
        migrations.AddField(
            model_name="scanexecution",
            name="status_message",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
